<?php

return [
    'cache' => [
        'hours' => 12,
        'keys' => [
            'inicio_eventos' => 'inicio_eventos',
            'inicio_testimonios' => 'inicio_testimonios_v2',
            'protagonistas_testimonios' => 'protagonistas_testimonios_v1',
            'recursos_listas_utiles' => 'recursos_listas_utiles_v2',
            'contacto_pagina_id' => 'contacto_pagina_id',
            'galeria.preescolar' => 'galeria_preescolar',
            'galeria.primaria' => 'galeria_primaria',
            'galeria.secundaria' => 'galeria_secundaria',
            'galeria.bachillerato' => 'galeria_bachillerato',
            'galeria.ib-en-discovery' => 'galeria_ib-en-discovery',
            'galeria.certificacion-de-ingles' => 'galeria_certificacion-de-ingles',
        ],
    ],

    'media' => [
        'disk' => 'videosyfotos',
        'video_extensions' => ['mp4', 'mov', 'webm', 'm4v'],
        'image_extensions' => ['jpg', 'jpeg', 'png', 'webp'],
    ],

    'contacto' => [
        'titulo' => 'Contacto',
        'subtitulo' => 'Informes y admisiones',
        'descripcion' => 'Compartenos tus datos y nos pondremos en contacto contigo para darte mas informacion sobre Colegio Discovery.',
        'direccion' => 'C. Vía Puebla 3611, José Garci-crespo, Residencial Cinco Bosques, 75855 Tehuacán, Pue., México',
        'telefono_principal' => '(238) 688 11 79',
        'telefono_secundario' => '(238) 102 18 17',
        'correo' => 'informes@colegio-discovery.edu.mx',
        'mapa_embed_url' => 'https://www.google.com/maps?q=Colegio%20Discovery%20Tehuacan%4018.4847219%2C-97.4150801&z=17&output=embed',
        'mapa_url' => 'https://www.google.com/maps/place/Colegio+Discovery+Tehuacan/@18.484529,-97.417467,17z/data=!4m6!3m5!1s0x85c5a32ab4097387:0x64c0781c4b44b94c!8m2!3d18.4847219!4d-97.4150801!16s%2Fg%2F1tcxk2pr?hl=es-US&entry=ttu&g_ep=EgoyMDI2MDUyMC4wIKXMDSoASAFQAw%3D%3D',
        'whatsapp_numero' => '+52 238 102 1817',
        'whatsapp_mensaje' => 'Hola, me gustaria recibir informacion sobre Colegio Discovery.',
    ],

    'tienda' => [
        'niveles' => [
            'Preescolar' => 'Preescolar',
            'Primaria' => 'Primaria',
            'Secundaria' => 'Secundaria',
            'Bachillerato' => 'Bachillerato',
        ],
        'estados_pedido' => [
            'incompleto' => 'Incompleto',
            'completado' => 'Completado',
        ],
        'productos' => [
            'cuaderno-profesional' => ['nombre' => 'Cuaderno profesional', 'nivel' => 'Todos los niveles', 'precio' => 45],
            'crayones-colores' => ['nombre' => 'Crayones y lapices de colores', 'nivel' => 'Preescolar y Primaria', 'precio' => 95],
            'resistol-pegamento' => ['nombre' => 'Resistol y pegamento escolar', 'nivel' => 'Preescolar y Primaria', 'precio' => 35],
            'hojas-folder' => ['nombre' => 'Hojas blancas y folder plastico', 'nivel' => 'Todos los niveles', 'precio' => 60],
            'lapices-plumas' => ['nombre' => 'Lapices y plumas', 'nivel' => 'Primaria, Secundaria y Bachillerato', 'precio' => 55],
            'tijeras' => ['nombre' => 'Tijeras escolares', 'nivel' => 'Preescolar y Primaria', 'precio' => 40],
            'juego-geometria' => ['nombre' => 'Juego de geometria', 'nivel' => 'Primaria, Secundaria y Bachillerato', 'precio' => 70],
            'diccionario' => ['nombre' => 'Diccionario escolar', 'nivel' => 'Primaria y Secundaria', 'precio' => 120],
            'carpeta-argollas' => ['nombre' => 'Carpeta de argollas', 'nivel' => 'Secundaria y Bachillerato', 'precio' => 85],
            'calculadora-cientifica' => ['nombre' => 'Calculadora cientifica', 'nivel' => 'Secundaria y Bachillerato', 'precio' => 280],
            'memoria-usb' => ['nombre' => 'Memoria USB', 'nivel' => 'Secundaria y Bachillerato', 'precio' => 140],
        ],
    ],

    'inicio' => [
        'eventos_default' => [
            [
                'titulo' => 'Evento Preescolar',
                'descripcion' => 'Actividades proximas para nuestras familias de preescolar.',
                'media_path' => 'Kinder/Colegio Discovery-15.jpg',
            ],
            [
                'titulo' => 'Evento Primaria',
                'descripcion' => 'Experiencias, proyectos y encuentros para nuestros explorers de primaria.',
                'media_path' => 'Elementary (Primaria)/Colegio Discovery-66.jpg',
            ],
            [
                'titulo' => 'Evento Secundaria',
                'descripcion' => 'Actividades academicas y de comunidad para middle school.',
                'media_path' => 'Middle (Secundaria)/Colegio Discovery-59.jpg',
            ],
        ],
        'logos_niveles' => [
            'preescolar' => 'Logos de niveles educativos/preescolar.png',
            'primaria' => 'Logos de niveles educativos/primaria.png',
            'secundaria' => 'Logos de niveles educativos/secundaria.png',
            'bachillerato' => 'Logos de niveles educativos/bachillerato.png',
        ],
    ],

    'oferta_academica' => [
        'preescolar' => [
            'titulo' => 'Preescolar',
            'subtitulo' => 'Primeros pasos con seguridad, juego y acompanamiento.',
            'descripcion' => 'Un entorno cercano para iniciar el aprendizaje con creatividad, bienestar emocional y bases bilingues.',
            'edad' => 'Maternal a Pre-primary',
            'color' => 'lime',
            'logo_path' => 'Logos de niveles educativos/logo preescolar.png',
            'imagen_clave' => 'preescolar',
            'imagen_default' => [
                'titulo' => 'Oferta Educativa - Preescolar',
                'referencia' => 'Imagen destacada para Preescolar en la vista Oferta Educativa.',
                'media_path' => 'Kinder/Colegio Discovery-15.jpg',
            ],
            'puntos' => ['Neuroaprendizaje', 'Ingles natural', 'Grupos reducidos'],
        ],
        'primaria' => [
            'titulo' => 'Primaria',
            'subtitulo' => 'Bases solidas para explorar, investigar y crear.',
            'descripcion' => 'Aprendizaje activo con enfoque bilingue, pensamiento logico, proyectos IB y desarrollo social.',
            'edad' => '1 a 6 grado',
            'color' => 'red',
            'logo_path' => 'Logos de niveles educativos/logo primaria.png',
            'imagen_clave' => 'primaria',
            'imagen_default' => [
                'titulo' => 'Oferta Educativa - Primaria',
                'referencia' => 'Imagen destacada para Primaria en la vista Oferta Educativa.',
                'media_path' => 'Elementary (Primaria)/Colegio Discovery-66.jpg',
            ],
            'puntos' => ['Ingles diario', 'Frances desde 5 grado', 'Tecnologia y arte'],
        ],
        'secundaria' => [
            'titulo' => 'Secundaria',
            'subtitulo' => 'Acompanamiento para descubrir voz, criterio y talentos.',
            'descripcion' => 'Formacion academica con idiomas, tecnologia, proyectos interdisciplinarios y bienestar emocional.',
            'edad' => '7 a 9 grado',
            'color' => 'blue',
            'logo_path' => 'Logos de niveles educativos/logo secundaria.png',
            'imagen_clave' => 'secundaria',
            'imagen_default' => [
                'titulo' => 'Oferta Educativa - Secundaria',
                'referencia' => 'Imagen destacada para Secundaria en la vista Oferta Educativa.',
                'media_path' => 'Middle (Secundaria)/Colegio Discovery-59.jpg',
            ],
            'puntos' => ['Tres idiomas', 'Deporte diario', 'Liderazgo y proyectos'],
        ],
        'bachillerato' => [
            'titulo' => 'Bachillerato',
            'subtitulo' => 'Preparacion universitaria con vision internacional.',
            'descripcion' => 'Una etapa retadora con Programa del Diploma IB, orientacion vocacional, liderazgo y proyectos reales.',
            'edad' => '10 a 12 grado',
            'color' => 'green',
            'logo_path' => 'Logos de niveles educativos/logo bachillerato.png',
            'imagen_clave' => 'bachillerato',
            'imagen_default' => [
                'titulo' => 'Oferta Educativa - Bachillerato',
                'referencia' => 'Imagen destacada para Bachillerato en la vista Oferta Educativa.',
                'media_path' => 'High (Prepa)/IMG_7346-scaled.jpg',
            ],
            'puntos' => ['Diploma IB', 'Orientacion vocacional', 'Becas universitarias'],
        ],
        'ib-en-discovery' => [
            'titulo' => 'IB en Discovery',
            'subtitulo' => 'Mentalidad internacional en la vida escolar.',
            'descripcion' => 'Un enfoque que fortalece investigacion, pensamiento critico, comunicacion y responsabilidad global.',
            'edad' => 'Enfoque transversal',
            'color' => 'amber',
            'logo_path' => 'Logos de niveles educativos/Logo IB cl.jpeg',
            'imagen_clave' => 'ib',
            'imagen_default' => [
                'titulo' => 'Oferta Educativa - IB en Discovery',
                'referencia' => 'Imagen destacada para IB en Discovery en la vista Oferta Educativa.',
                'media_path' => 'Logos de niveles educativos/Logo IB cl.jpeg',
            ],
            'puntos' => ['Perfil IB', 'Indagacion', 'Accion con impacto'],
        ],
        'certificacion-de-ingles' => [
            'titulo' => 'Certificacion de Ingles',
            'subtitulo' => 'Metas claras para avanzar con confianza.',
            'descripcion' => 'Acompanamiento academico para fortalecer reading, writing, listening y speaking con objetivos medibles.',
            'edad' => 'Preparacion continua',
            'color' => 'sky',
            'logo_path' => null,
            'imagen_clave' => 'certificacion_ingles',
            'imagen_default' => [
                'titulo' => 'Oferta Educativa - Certificacion de Ingles',
                'referencia' => 'Imagen destacada para Certificacion de Ingles en la vista Oferta Educativa.',
            ],
            'puntos' => ['Practica guiada', 'Habilidades comunicativas', 'Seguimiento academico'],
        ],
    ],

    'protagonistas' => [
        'niveles' => [
            ['titulo' => 'Preescolar', 'clave' => 'preescolar', 'color' => 'bg-lime-500', 'referencia' => 'Imagen para representar Preescolar dentro de Comunidad.', 'media_path' => 'Kinder/Colegio Discovery-15.jpg'],
            ['titulo' => 'Primaria', 'clave' => 'primaria', 'color' => 'bg-red-600', 'referencia' => 'Imagen para representar Primaria dentro de Comunidad.', 'media_path' => 'Elementary (Primaria)/Colegio Discovery-66.jpg'],
            ['titulo' => 'Secundaria', 'clave' => 'secundaria', 'color' => 'bg-blue-700', 'referencia' => 'Imagen para representar Secundaria dentro de Comunidad.', 'media_path' => 'Middle (Secundaria)/Colegio Discovery-61.jpg'],
            ['titulo' => 'Bachillerato', 'clave' => 'bachillerato', 'color' => 'bg-green-600', 'referencia' => 'Imagen para representar Bachillerato dentro de Comunidad.', 'media_path' => 'Logos de niveles educativos/bachillerato.png'],
        ],
        'protagonistas' => [
            'alumnos' => ['titulo' => 'Comunidad - Alumnos', 'color' => 'bg-red-600', 'referencia' => 'Imagen para representar a los alumnos en la seccion Quienes hacen viva nuestra comunidad.', 'media_path' => 'Elementary (Primaria)/Colegio Discovery-66.jpg'],
            'docentes' => ['titulo' => 'Comunidad - Docentes', 'color' => 'bg-blue-700', 'referencia' => 'Imagen para representar a docentes en la seccion Quienes hacen viva nuestra comunidad.', 'media_path' => 'Middle (Secundaria)/Colegio Discovery-61.jpg'],
            'padres' => ['titulo' => 'Comunidad - Familias', 'color' => 'bg-lime-500', 'referencia' => 'Imagen para representar a familias en la seccion Quienes hacen viva nuestra comunidad.', 'media_path' => 'Kinder/Colegio Discovery-15.jpg'],
            'alumni' => ['titulo' => 'Comunidad - Alumni', 'color' => 'bg-green-600', 'referencia' => 'Imagen para representar a alumni en la seccion Quienes hacen viva nuestra comunidad.', 'media_path' => 'High (Prepa)/IMG_7346-scaled.jpg'],
        ],
    ],

    'niveles' => [
        'carpetas_galeria' => [
            'preescolar' => 'Kinder',
            'primaria' => 'Elementary (Primaria)',
            'secundaria' => 'Middle (Secundaria)',
            'bachillerato' => 'High (Prepa)',
        ],
        'definiciones' => [
            'preescolar' => [
                'titulo' => 'Preescolar',
                'descripcion' => 'Un entorno cercano para iniciar el aprendizaje con seguridad, creatividad y acompanamiento.',
                'logo_path' => 'Logos de niveles educativos/logo preescolar.png',
                'hoja_informativa_path' => 'Hojas informativas/Kinder _ hoja informativa.pdf.pdf',
                'modelo_academico_path' => 'Modelos educativos/modelo educativo kínder.png',
                'informacion' => [
                    'titulo' => 'El kinder ideal para tus hijos',
                    'intro' => 'Una infancia feliz, segura y bilingue, con programas de neuroaprendizaje y bases solidas para Elementary.',
                    'destacados' => [
                        ['titulo' => 'Acompanamiento', 'texto' => 'Grupos reducidos de 14 a 24 alumnos, bienestar emocional y seguimiento cercano en cada etapa.'],
                        ['titulo' => 'Aprendizaje', 'texto' => 'Neuromotor, Audiomotor, Spark y Bancubi fortalecen lenguaje, pensamiento logico y madurez neurologica.'],
                        ['titulo' => 'Comunidad', 'texto' => 'Crecen en un entorno de amor, respeto y seguridad, con valores IB y mentalidad abierta.'],
                    ],
                    'puntos' => [
                        'Programas de neuroaprendizaje: Neuromotor, Audiomotor y Spark.',
                        'Aprendizaje natural en ingles y espanol con estrategias multisensoriales.',
                        'Programas alineados al Bachillerato Internacional desde los primeros anos.',
                        'Grupos reducidos de 14 a 24 alumnos con atencion personalizada.',
                        'Bienestar emocional, expresion oral y acompanamiento cercano.',
                    ],
                    'secciones' => [
                        ['titulo' => 'Estimulacion para cuerpo y mente', 'texto' => 'Neuromotor y Audiomotor fortalecen coordinacion, atencion, creatividad, autodominio fisico y madurez neurologica.'],
                        ['titulo' => 'Aprendizaje en dos idiomas', 'texto' => 'Spark impulsa lectoescritura, vocabulario, comprension y expresion en ingles y espanol desde los primeros anos.'],
                        ['titulo' => 'Pensamiento logico jugando', 'texto' => 'Con Bancubi aprenden matematicas de forma concreta: clasifican, ordenan, comparan y resuelven problemas manipulando objetos reales.'],
                        ['titulo' => 'Crecimiento en comunidad', 'texto' => 'Crecen en un entorno de amor, respeto y seguridad, con valores del perfil IB, empatia y mentalidad abierta.'],
                    ],
                    'experiencias' => ['Convivio de Navidad', 'Clase Neuromotora', 'Visita de Pre-primary a Elementary', 'Profesiones y Oficios', 'Festival de la Primavera', 'Dia del nino y la nina'],
                ],
            ],
            'primaria' => [
                'titulo' => 'Primaria',
                'descripcion' => 'Bases academicas solidas, valores y experiencias que despiertan la curiosidad.',
                'logo_path' => 'Logos de niveles educativos/logo primaria.png',
                'hoja_informativa_path' => 'Hojas informativas/Elementary _hoja informativa.pdf',
                'modelo_academico_path' => 'Modelos educativos/modelo educativo elementary.png',
                'informacion' => [
                    'titulo' => 'La primaria para tus hijos',
                    'intro' => 'Un entorno bilingue y trilingue donde los alumnos desarrollan mentalidad internacional, creatividad, tecnologia y bienestar emocional.',
                    'destacados' => [
                        ['titulo' => 'Acompanamiento', 'texto' => 'Atencion academica y emocional para que cada alumno avance con confianza, curiosidad y autonomia.'],
                        ['titulo' => 'Aprendizaje', 'texto' => 'Tres bloques diarios en ingles, frances desde 5 grado, tecnologia, arte y unidades de indagacion IB.'],
                        ['titulo' => 'Comunidad', 'texto' => 'Deporte diario, academias, mini olimpiadas y proyectos que fortalecen colaboracion y pertenencia.'],
                    ],
                    'puntos' => [
                        'Tres bloques diarios en ingles con materias como Science y Civics.',
                        'Frances desde 5 grado de primaria como tercer idioma.',
                        'Mock Cambridge desde 3 grado de primaria para practicar reading, writing, listening y speaking.',
                        'Unidades de indagacion del modelo IB para investigar, cuestionar y resolver problemas reales.',
                        'Artes, deporte diario y academias vespertinas como futbol, basquetbol, ajedrez, origami, atletismo y UrbanKids.',
                    ],
                    'secciones' => [
                        ['titulo' => 'Formacion bilingue y trilingue', 'texto' => 'Aprenden ingles en un entorno de inmersion y suman frances para ampliar su vision como ciudadanos globales.'],
                        ['titulo' => 'Perfil IB y pensamiento global', 'texto' => 'Trabajan atributos como ser pensadores, informados, comunicadores, solidarios y de mentalidad abierta.'],
                        ['titulo' => 'Pensamiento logico y algoritmico', 'texto' => 'Tecnologia y concursos de programacion fortalecen analisis, secuenciacion, creatividad y toma de decisiones.'],
                        ['titulo' => 'Cuerpo, atencion y creatividad', 'texto' => 'Neuromotor continua en Elementary junto con deporte diario y artes integradas para una formacion equilibrada.'],
                    ],
                    'experiencias' => ['Mini Olimpiadas', 'Obras de teatro', 'Festival Dia del Nino', 'Graduacion', 'Unidades de Indagacion'],
                ],
            ],
            'secundaria' => [
                'titulo' => 'Secundaria',
                'descripcion' => 'Formacion integral con tecnologia, proyectos y desarrollo personal.',
                'logo_path' => 'Logos de niveles educativos/logo secundaria.png',
                'hoja_informativa_path' => 'Hojas informativas/Secundaria _hoja informativa.pdf.pdf',
                'modelo_academico_path' => 'Modelos educativos/modelo educativo middle.png',
                'informacion' => [
                    'titulo' => 'La secundaria que ayuda a tus hijos a convertirse en su mejor version',
                    'intro' => 'Middle School es la etapa donde los jovenes despiertan su voz, definen su camino y conectan localmente con una vision global.',
                    'destacados' => [
                        ['titulo' => 'Acompanamiento', 'texto' => 'Preceptoria, bienestar emocional y habilidades de autogestion para una etapa de cambios importantes.'],
                        ['titulo' => 'Aprendizaje', 'texto' => 'Ingles, espanol y frances, proyectos interdisciplinarios y enfoques de aprendizaje para pensar e investigar mejor.'],
                        ['titulo' => 'Comunidad', 'texto' => 'Deporte diario, DKMUN, WASP, arte y clanes para desarrollar liderazgo, identidad y trabajo en equipo.'],
                    ],
                    'puntos' => [
                        'Ingles, espanol y frances con mas de 15 bloques a la semana.',
                        'Enfoques de aprendizaje: pensamiento, autogestion, comunicacion, investigacion y habilidades sociales.',
                        'Proyectos interdisciplinarios con mentalidad internacional.',
                        'Deporte diario: futbol, basquetbol, voleibol o tenis.',
                        'Bienestar emocional y preceptoria hasta el ultimo ano.',
                    ],
                    'secciones' => [
                        ['titulo' => 'Idiomas para comunicarse con el mundo', 'texto' => 'Viven el ingles todos los dias, incorporan frances y se preparan para certificaciones como Cambridge y Lengua B del Programa Diploma.'],
                        ['titulo' => 'Deporte diario', 'texto' => 'La practica deportiva fortalece salud fisica, disciplina, autoestima, trabajo en equipo y habitos saludables.'],
                        ['titulo' => 'Liderazgo y proyectos globales', 'texto' => 'Programas como DKMun y WASP desarrollan investigacion, debate, diplomacia y liderazgo desde edades tempranas.'],
                        ['titulo' => 'Talentos y pasiones', 'texto' => 'Exploran arte, ciencia, ferias escolares y experiencias que conectan lo aprendido con el mundo real.'],
                    ],
                    'experiencias' => ['Dia del Arte', 'Deportes', 'Aniversario', 'Clanes', 'Presentaciones'],
                ],
            ],
            'bachillerato' => [
                'titulo' => 'Bachillerato',
                'descripcion' => 'Preparacion para la universidad con orientacion vocacional y alto nivel academico.',
                'logo_path' => 'Logos de niveles educativos/logo bachillerato.png',
                'hoja_informativa_path' => 'Hojas informativas/High school _ hoja informativa.pdf.pdf',
                'modelo_academico_path' => 'Modelos educativos/modelo educativo high.png',
                'informacion' => [
                    'titulo' => 'Un bachillerato que te reta, forma y tambien se disfruta',
                    'intro' => 'Preparacion universitaria con Programa del Diploma IB, orientacion vocacional, idiomas, liderazgo y proyectos reales.',
                    'destacados' => [
                        ['titulo' => 'Acompanamiento', 'texto' => 'Orientacion vocacional, asesoria para admisiones y seguimiento individual rumbo a universidad.'],
                        ['titulo' => 'Aprendizaje', 'texto' => 'Programa del Diploma IB, Teoria del Conocimiento, CAS, idiomas y pensamiento critico aplicado.'],
                        ['titulo' => 'Comunidad', 'texto' => 'DKMUN, proyectos IB, arte, deporte diario e impacto social para fortalecer liderazgo y expresion.'],
                    ],
                    'puntos' => [
                        'Bachillerato IB oficial con validez internacional.',
                        'Programa del Diploma y desarrollo del perfil IB.',
                        'Ingles, espanol y frances con 15 bloques semanales en ingles.',
                        'Mas del 70% de egresados obtiene becas en universidades de Mexico y el extranjero.',
                        'Orientacion vocacional, asesoria para admisiones y seguimiento individual.',
                    ],
                    'secciones' => [
                        ['titulo' => 'Pensamiento global', 'texto' => 'Teoria del Conocimiento y CAS fortalecen pensamiento critico, vision internacional y capacidad de tomar decisiones.'],
                        ['titulo' => 'Certificaciones e idiomas', 'texto' => 'La formacion en ingles y frances prepara para comunicar argumentos, escribir ensayos y abrir puertas universitarias.'],
                        ['titulo' => 'Debates y liderazgo', 'texto' => 'DKMUN permite negociar, argumentar, proponer soluciones y representar paises en asuntos internacionales.'],
                        ['titulo' => 'Impacto social y expresion', 'texto' => 'CAS, arte y deporte diario hacen que cada estudiante participe en proyectos culturales, sociales, ambientales o deportivos.'],
                    ],
                    'experiencias' => ['Expo Arte', 'Graduacion', 'Dia del Estudiante', 'DKMUN', 'Proyectos IB'],
                ],
            ],
            'ib-en-discovery' => [
                'titulo' => 'IB en Discovery',
                'descripcion' => 'Una experiencia educativa con enfoque internacional y pensamiento critico.',
                'logo_path' => 'Logos de niveles educativos/Logo IB cl.jpeg',
            ],
            'certificacion-de-ingles' => [
                'titulo' => 'Certificacion de Ingles',
                'descripcion' => 'Desarrollo del idioma ingles con metas claras y acompanamiento academico.',
            ],
        ],
    ],

    'temas_niveles' => [
        'preescolar' => [
            'hero' => 'bg-lime-500 text-black',
            'heading' => 'text-lime-800',
            'eyebrow' => 'text-lime-800',
            'soft' => 'bg-lime-50 border-lime-300',
            'dot' => 'bg-lime-500',
            'button' => 'bg-lime-500 text-black hover:bg-lime-600',
            'chip' => 'text-lime-800',
            'bar' => 'bg-lime-500',
            'heroText' => 'text-black',
            'heroMuted' => 'text-black',
        ],
        'primaria' => [
            'hero' => 'bg-red-600 text-white',
            'heading' => 'text-red-600',
            'eyebrow' => 'text-red-600',
            'soft' => 'bg-red-50 border-red-200',
            'dot' => 'bg-red-600',
            'button' => 'bg-red-600 text-white hover:bg-red-700',
            'chip' => 'text-red-600',
            'bar' => 'bg-red-600',
            'heroText' => 'text-white',
            'heroMuted' => 'text-red-50',
        ],
        'secundaria' => [
            'hero' => 'bg-blue-700 text-white',
            'heading' => 'text-blue-700',
            'eyebrow' => 'text-blue-700',
            'soft' => 'bg-blue-50 border-blue-100',
            'dot' => 'bg-blue-700',
            'button' => 'bg-blue-700 text-white hover:bg-blue-800',
            'chip' => 'text-blue-700',
            'bar' => 'bg-blue-700',
            'heroText' => 'text-white',
            'heroMuted' => 'text-blue-50',
        ],
        'bachillerato' => [
            'hero' => 'bg-green-500 text-white',
            'heading' => 'text-green-600',
            'eyebrow' => 'text-green-600',
            'soft' => 'bg-green-50 border-green-200',
            'dot' => 'bg-green-500',
            'button' => 'bg-green-500 text-white hover:bg-green-600',
            'chip' => 'text-green-600',
            'bar' => 'bg-green-500',
            'heroText' => 'text-white',
            'heroMuted' => 'text-green-50',
        ],
        'default' => [
            'hero' => 'bg-blue-700 text-white',
            'heading' => 'text-blue-700',
            'eyebrow' => 'text-blue-700',
            'soft' => 'bg-blue-50 border-blue-100',
            'dot' => 'bg-blue-700',
            'button' => 'bg-blue-700 text-white hover:bg-blue-800',
            'chip' => 'text-blue-700',
            'bar' => 'bg-blue-700',
            'heroText' => 'text-white',
            'heroMuted' => 'text-blue-50',
        ],
    ],
];
