<?php

return [
    'cache' => [
        'hours' => 12,
        'keys' => [
            'inicio_eventos' => 'inicio_eventos',
            'inicio_testimonios' => 'inicio_testimonios_v2',
            'nosotros_historia' => 'nosotros_historia_v1',
            'protagonistas_testimonios' => 'protagonistas_testimonios_v1',
            'recursos_listas_utiles' => 'recursos_listas_utiles_v2',
            'contacto_pagina_id' => 'contacto_pagina_id',
            'pagina_contenido.inicio' => 'pagina_contenido_inicio',
            'pagina_contenido.nosotros' => 'pagina_contenido_nosotros',
            'pagina_contenido.oferta-academica' => 'pagina_contenido_oferta_academica',
            'pagina_contenido.protagonistas' => 'pagina_contenido_protagonistas',
            'pagina_contenido.contacto' => 'pagina_contenido_contacto',
            'galeria.preescolar' => 'galeria_preescolar_actuales_v1',
            'galeria.primaria' => 'galeria_primaria_actuales_v1',
            'galeria.secundaria' => 'galeria_secundaria_actuales_v1',
            'galeria.bachillerato' => 'galeria_bachillerato_actuales_v1',
            'galeria.ib-en-discovery' => 'galeria_ib-en-discovery',
            'galeria.certificacion-de-ingles' => 'galeria_certificacion-de-ingles',
        ],
    ],

    'media' => [
        'disk' => 'videosyfotos',
        'video_extensions' => ['mp4', 'mov', 'webm', 'm4v'],
        'image_extensions' => ['jpg', 'jpeg', 'png', 'webp'],
    ],

    'contacto' => [
        'titulo' => 'Contacto',
        'subtitulo' => 'Informes y admisiones',
        'descripcion' => 'Compartenos tus datos y nos pondremos en contacto contigo para darte mas informacion sobre Colegio Discovery.',
        'direccion' => 'C. Vía Puebla 3611, José Garci-crespo, Residencial Cinco Bosques, 75855 Tehuacán, Pue., México',
        'telefono_principal' => '(238) 688 11 79',
        'telefono_secundario' => '(238) 102 18 17',
        'correo' => 'informes@colegio-discovery.edu.mx',
        'mapa_embed_url' => 'https://www.google.com/maps?q=Colegio%20Discovery%20Tehuacan%4018.4847219%2C-97.4150801&z=17&output=embed',
        'mapa_url' => 'https://www.google.com/maps/place/Colegio+Discovery+Tehuacan/@18.484529,-97.417467,17z/data=!4m6!3m5!1s0x85c5a32ab4097387:0x64c0781c4b44b94c!8m2!3d18.4847219!4d-97.4150801!16s%2Fg%2F1tcxk2pr?hl=es-US&entry=ttu&g_ep=EgoyMDI2MDUyMC4wIKXMDSoASAFQAw%3D%3D',
        'whatsapp_numero' => '+52 238 102 1817',
        'whatsapp_mensaje' => 'Hola, me gustaria recibir informacion sobre Colegio Discovery.',
    ],

    'inicio' => [
        'eventos_default' => [
            [
                'titulo' => 'Evento Preescolar',
                'descripcion' => 'Actividades proximas para nuestras familias de preescolar.',
                'media_path' => 'Kinder fotos actuales/IMG_5775.JPG',
            ],
            [
                'titulo' => 'Evento Primaria',
                'descripcion' => 'Experiencias, proyectos y encuentros para nuestros explorers de primaria.',
                'media_path' => 'Elementary fotos actuales/IMG_5684.JPG',
            ],
            [
                'titulo' => 'Evento Secundaria',
                'descripcion' => 'Actividades academicas y de comunidad para middle school.',
                'media_path' => 'Middle fotos actuales/IMG_5867.JPG',
            ],
        ],
        'logos_niveles' => [
            'preescolar' => 'Logos de niveles educativos/preescolar.png',
            'primaria' => 'Logos de niveles educativos/primaria.png',
            'secundaria' => 'Logos de niveles educativos/secundaria.png',
            'bachillerato' => 'Logos de niveles educativos/bachillerato.png',
        ],
    ],

    'oferta_academica' => [
        'preescolar' => [
            'titulo' => 'Preescolar',
            'subtitulo' => 'Primeros pasos con seguridad, juego y acompanamiento.',
            'descripcion' => 'Un entorno cercano para iniciar el aprendizaje con creatividad, bienestar emocional y bases bilingues.',
            'edad' => 'Maternal a Pre-primary',
            'color' => 'lime',
            'logo_path' => 'Logos de niveles educativos/logo preescolar.png',
            'imagen_clave' => 'preescolar',
            'imagen_default' => [
                'titulo' => 'Oferta Educativa - Preescolar',
                'referencia' => 'Imagen destacada para Preescolar en la vista Oferta Educativa.',
                'media_path' => 'Kinder fotos actuales/IMG_5775.JPG',
            ],
            'puntos' => ['Neuroaprendizaje', 'Ingles natural', 'Grupos reducidos'],
        ],
        'primaria' => [
            'titulo' => 'Primaria',
            'subtitulo' => 'Bases solidas para explorar, investigar y crear.',
            'descripcion' => 'Aprendizaje activo con enfoque bilingue, pensamiento logico, proyectos IB y desarrollo social.',
            'edad' => '1 a 6 grado',
            'color' => 'red',
            'logo_path' => 'Logos de niveles educativos/logo primaria.png',
            'imagen_clave' => 'primaria',
            'imagen_default' => [
                'titulo' => 'Oferta Educativa - Primaria',
                'referencia' => 'Imagen destacada para Primaria en la vista Oferta Educativa.',
                'media_path' => 'Elementary fotos actuales/IMG_5684.JPG',
            ],
            'puntos' => ['Ingles diario', 'Frances desde 5 grado', 'Tecnologia y arte'],
        ],
        'secundaria' => [
            'titulo' => 'Secundaria',
            'subtitulo' => 'Acompanamiento para descubrir voz, criterio y talentos.',
            'descripcion' => 'Formacion academica con idiomas, tecnologia, proyectos interdisciplinarios y bienestar emocional.',
            'edad' => '7 a 9 grado',
            'color' => 'blue',
            'logo_path' => 'Logos de niveles educativos/logo secundaria.png',
            'imagen_clave' => 'secundaria',
            'imagen_default' => [
                'titulo' => 'Oferta Educativa - Secundaria',
                'referencia' => 'Imagen destacada para Secundaria en la vista Oferta Educativa.',
                'media_path' => 'Middle fotos actuales/IMG_5867.JPG',
            ],
            'puntos' => ['Tres idiomas', 'Deporte diario', 'Proyectos con impacto'],
        ],
        'bachillerato' => [
            'titulo' => 'Bachillerato',
            'subtitulo' => 'Preparacion universitaria con vision internacional.',
            'descripcion' => 'Una etapa retadora con Programa del Diploma IB, orientacion vocacional y proyectos reales.',
            'edad' => '10 a 12 grado',
            'color' => 'green',
            'logo_path' => 'Logos de niveles educativos/logo bachillerato.png',
            'imagen_clave' => 'bachillerato',
            'imagen_default' => [
                'titulo' => 'Oferta Educativa - Bachillerato',
                'referencia' => 'Imagen destacada para Bachillerato en la vista Oferta Educativa.',
                'media_path' => 'High (Prepa)/BACHILLERATO-MOSAICO-5-scaled.jpg',
            ],
            'puntos' => ['Diploma IB', 'Orientacion vocacional', 'Becas universitarias'],
        ],
        'ib-en-discovery' => [
            'titulo' => 'IB en Discovery',
            'subtitulo' => 'Mentalidad internacional en la vida escolar.',
            'descripcion' => 'Un enfoque que fortalece investigacion, pensamiento critico, comunicacion y responsabilidad global.',
            'edad' => 'Enfoque transversal',
            'color' => 'amber',
            'logo_path' => 'Logos de niveles educativos/Logo IB cl.jpeg',
            'imagen_clave' => 'ib',
            'imagen_default' => [
                'titulo' => 'Oferta Educativa - IB en Discovery',
                'referencia' => 'Imagen destacada para IB en Discovery en la vista Oferta Educativa.',
                'media_path' => 'Logos de niveles educativos/Logo IB cl.jpeg',
            ],
            'puntos' => ['Perfil IB', 'Indagacion', 'Accion con impacto'],
        ],
        'certificacion-de-ingles' => [
            'titulo' => 'Certificacion de Ingles',
            'subtitulo' => 'Metas claras para avanzar con confianza.',
            'descripcion' => 'Acompanamiento academico para fortalecer reading, writing, listening y speaking con objetivos medibles.',
            'edad' => 'Preparacion continua',
            'color' => 'sky',
            'logo_path' => null,
            'imagen_clave' => 'certificacion_ingles',
            'imagen_default' => [
                'titulo' => 'Oferta Educativa - Certificacion de Ingles',
                'referencia' => 'Imagen destacada para Certificacion de Ingles en la vista Oferta Educativa.',
                'media_path' => 'Certificacion fotos/unicam.jpg',
            ],
            'puntos' => ['Practica guiada', 'Habilidades comunicativas', 'Seguimiento academico'],
        ],
    ],

    'protagonistas' => [
        'niveles' => [
            ['titulo' => 'Preescolar', 'clave' => 'preescolar', 'color' => 'bg-lime-500', 'referencia' => 'Imagen para representar Preescolar dentro de Comunidad.', 'media_path' => 'Kinder fotos actuales/IMG_5775.JPG'],
            ['titulo' => 'Primaria', 'clave' => 'primaria', 'color' => 'bg-red-600', 'referencia' => 'Imagen para representar Primaria dentro de Comunidad.', 'media_path' => 'Elementary fotos actuales/IMG_5684.JPG'],
            ['titulo' => 'Secundaria', 'clave' => 'secundaria', 'color' => 'bg-blue-700', 'referencia' => 'Imagen para representar Secundaria dentro de Comunidad.', 'media_path' => 'Middle fotos actuales/IMG_5867.JPG'],
            ['titulo' => 'Bachillerato', 'clave' => 'bachillerato', 'color' => 'bg-green-600', 'referencia' => 'Imagen para representar Bachillerato dentro de Comunidad.', 'media_path' => 'High fotos actuales/1234.jpg'],
        ],
        'protagonistas' => [
            'alumnos' => ['titulo' => 'Comunidad - Explorers', 'color' => 'bg-red-600', 'referencia' => 'Imagen para representar a los Explorers en la seccion Quienes hacen viva nuestra comunidad.', 'media_path' => 'Comunidad Explorers/1234.jpg', 'media_directory' => 'Comunidad Explorers'],
            'docentes' => ['titulo' => 'Comunidad - Docentes', 'color' => 'bg-blue-700', 'referencia' => 'Imagen para representar a docentes en la seccion Quienes hacen viva nuestra comunidad.', 'media_path' => 'Fotos Docentes/1.png', 'media_directory' => 'Fotos Docentes'],
            'padres' => ['titulo' => 'Comunidad - Familias', 'color' => 'bg-lime-500', 'referencia' => 'Imagen para representar a familias en la seccion Quienes hacen viva nuestra comunidad.', 'media_path' => 'Fotos Padres de Familia/3.png', 'media_directory' => 'Fotos Padres de Familia'],
            'alumni' => ['titulo' => 'Comunidad - Alumni', 'color' => 'bg-green-600', 'referencia' => 'Imagen para representar a alumni en la seccion Quienes hacen viva nuestra comunidad.', 'media_path' => 'Fotos Alumni/001.JPG', 'media_directory' => 'Fotos Alumni'],
        ],
    ],

    'niveles' => [
        'carpetas_galeria' => [
            'preescolar' => 'Kinder fotos actuales',
            'primaria' => 'Elementary fotos actuales',
            'secundaria' => 'Middle fotos actuales',
            'bachillerato' => 'High fotos actuales',
        ],
        'definiciones' => [
            'preescolar' => [
                'titulo' => 'Preescolar',
                'descripcion' => 'Un entorno cercano para iniciar el aprendizaje con seguridad, creatividad y acompanamiento.',
                'logo_path' => 'Logos de niveles educativos/logo preescolar.png',
                'logo_extendido_path' => 'Logos de niveles educativos/Preescolar extendido.jpeg',
                'hoja_informativa_path' => 'Hojas informativas/Kinder _ hoja informativa.pdf.pdf',
                'modelo_academico_path' => 'Modelos educativos/modelo educativo kínder.png',
                'informacion' => [
                    'titulo' => 'El kinder ideal para tus hijos',
                    'intro' => 'Una infancia feliz, segura y bilingue, con programas de neuroaprendizaje y bases solidas para Elementary.',
                    'destacados' => [
                        ['titulo' => 'Acompanamiento', 'texto' => 'Grupos reducidos de 14 a 24 Explorers, bienestar emocional y seguimiento cercano en cada etapa.'],
                        ['titulo' => 'Aprendizaje', 'texto' => 'Neuromotor, Audiomotor, Spark y Bancubi fortalecen lenguaje, pensamiento logico y madurez neurologica.'],
                        ['titulo' => 'Comunidad', 'texto' => 'Crecen en un entorno de amor, respeto y seguridad, con valores IB y mentalidad abierta.'],
                    ],
                    'puntos' => [
                        'Programas de neuroaprendizaje: Neuromotor, Audiomotor y Spark.',
                        'Aprendizaje natural en ingles y espanol con estrategias multisensoriales.',
                        'Programas alineados al Bachillerato Internacional desde los primeros anos.',
                        'Grupos reducidos de 14 a 24 Explorers con atencion personalizada.',
                        'Bienestar emocional, expresion oral y acompanamiento cercano.',
                    ],
                    'secciones' => [
                        ['titulo' => 'Estimulacion para cuerpo y mente', 'texto' => 'Neuromotor y Audiomotor fortalecen coordinacion, atencion, creatividad, autodominio fisico y madurez neurologica.'],
                        ['titulo' => 'Aprendizaje en dos idiomas', 'texto' => 'Spark impulsa lectoescritura, vocabulario, comprension y expresion en ingles y espanol desde los primeros anos.'],
                        ['titulo' => 'Pensamiento logico jugando', 'texto' => 'Con Bancubi aprenden matematicas de forma concreta: clasifican, ordenan, comparan y resuelven problemas manipulando objetos reales.'],
                        ['titulo' => 'Crecimiento en comunidad', 'texto' => 'Crecen en un entorno de amor, respeto y seguridad, con valores del perfil IB, empatia y mentalidad abierta.'],
                    ],
                    'experiencias' => ['Convivio de Navidad', 'Clase Neuromotora', 'Visita de Pre-primary a Elementary', 'Profesiones y Oficios', 'Festival de la Primavera', 'Dia del nino y la nina'],
                ],
            ],
            'primaria' => [
                'titulo' => 'Primaria',
                'descripcion' => 'Bases academicas solidas, valores y experiencias que despiertan la curiosidad.',
                'logo_path' => 'Logos de niveles educativos/logo primaria.png',
                'logo_extendido_path' => 'Logos de niveles educativos/Primaria extendido.jpeg',
                'hoja_informativa_path' => 'Hojas informativas/Elementary _hoja informativa.pdf',
                'modelo_academico_path' => 'Modelos educativos/modelo educativo elementary.png',
                'informacion' => [
                    'titulo' => 'La primaria para tus hijos',
                    'intro' => 'Un entorno bilingue y trilingue donde los Explorers desarrollan mentalidad internacional, creatividad, tecnologia y bienestar emocional.',
                    'destacados' => [
                        ['titulo' => 'Acompanamiento', 'texto' => 'Atencion academica y emocional para que cada Explorer avance con confianza, curiosidad y autonomia.'],
                        ['titulo' => 'Aprendizaje', 'texto' => 'Tres bloques diarios en ingles, frances desde 5 grado, tecnologia, arte y unidades de indagacion IB.'],
                        ['titulo' => 'Comunidad', 'texto' => 'Deporte diario, academias, mini olimpiadas y proyectos que fortalecen colaboracion y pertenencia.'],
                    ],
                    'puntos' => [
                        'Tres bloques diarios en ingles con materias como Science y Civics.',
                        'Frances desde 5 grado de primaria como tercer idioma.',
                        'Mock Cambridge desde 3 grado de primaria para practicar reading, writing, listening y speaking.',
                        'Unidades de indagacion del modelo IB para investigar, cuestionar y resolver problemas reales.',
                        'Artes, deporte diario y academias vespertinas como futbol, basquetbol, ajedrez, origami, atletismo y UrbanKids.',
                    ],
                    'secciones' => [
                        ['titulo' => 'Formacion bilingue y trilingue', 'texto' => 'Aprenden ingles en un entorno de inmersion y suman frances para ampliar su vision como ciudadanos globales.'],
                        ['titulo' => 'Perfil IB y pensamiento global', 'texto' => 'Trabajan atributos como ser pensadores, informados, comunicadores, solidarios y de mentalidad abierta.'],
                        ['titulo' => 'Pensamiento logico y algoritmico', 'texto' => 'Tecnologia y concursos de programacion fortalecen analisis, secuenciacion, creatividad y toma de decisiones.'],
                        ['titulo' => 'Cuerpo, atencion y creatividad', 'texto' => 'Neuromotor continua en Elementary junto con deporte diario y artes integradas para una formacion equilibrada.'],
                    ],
                    'experiencias' => ['Mini Olimpiadas', 'Obras de teatro', 'Festival Dia del Nino', 'Graduacion', 'Unidades de Indagacion'],
                ],
            ],
            'secundaria' => [
                'titulo' => 'Secundaria',
                'descripcion' => 'Formacion integral con tecnologia, proyectos y desarrollo personal.',
                'logo_path' => 'Logos de niveles educativos/logo secundaria.png',
                'logo_extendido_path' => 'Logos de niveles educativos/Secundaria extendido.jpeg',
                'hoja_informativa_path' => 'Hojas informativas/Secundaria _hoja informativa.pdf.pdf',
                'modelo_academico_path' => 'Modelos educativos/modelo educativo middle.png',
                'informacion' => [
                    'titulo' => 'La secundaria que ayuda a tus hijos a convertirse en su mejor version',
                    'intro' => 'Middle School es la etapa donde los jovenes despiertan su voz, definen su camino y conectan localmente con una vision global.',
                    'destacados' => [
                        ['titulo' => 'Acompanamiento', 'texto' => 'Preceptoria, bienestar emocional y habilidades de autogestion para una etapa de cambios importantes.'],
                        ['titulo' => 'Aprendizaje', 'texto' => 'Ingles, espanol y frances, proyectos interdisciplinarios y enfoques de aprendizaje para pensar e investigar mejor.'],
                        ['titulo' => 'Comunidad', 'texto' => 'Deporte diario, DKMUN, WASP, arte y clanes para desarrollar iniciativa, identidad y trabajo en equipo.'],
                    ],
                    'puntos' => [
                        'Ingles, espanol y frances con mas de 15 bloques a la semana.',
                        'Enfoques de aprendizaje: pensamiento, autogestion, comunicacion, investigacion y habilidades sociales.',
                        'Proyectos interdisciplinarios con mentalidad internacional.',
                        'Deporte diario: futbol, basquetbol, voleibol o tenis.',
                        'Bienestar emocional y preceptoria hasta el ultimo ano.',
                    ],
                    'secciones' => [
                        ['titulo' => 'Idiomas para comunicarse con el mundo', 'texto' => 'Viven el ingles todos los dias, incorporan frances y se preparan para certificaciones como Cambridge y Lengua B del Programa Diploma.'],
                        ['titulo' => 'Deporte diario', 'texto' => 'La practica deportiva fortalece salud fisica, disciplina, autoestima, trabajo en equipo y habitos saludables.'],
                        ['titulo' => 'Proyectos globales', 'texto' => 'Programas como DKMun y WASP desarrollan investigacion, debate, diplomacia e iniciativa desde edades tempranas.'],
                        ['titulo' => 'Talentos y pasiones', 'texto' => 'Exploran arte, ciencia, ferias escolares y experiencias que conectan lo aprendido con el mundo real.'],
                    ],
                    'experiencias' => ['Dia del Arte', 'Deportes', 'Aniversario', 'Clanes', 'Presentaciones'],
                ],
            ],
            'bachillerato' => [
                'titulo' => 'Bachillerato',
                'descripcion' => 'Preparacion para la universidad con orientacion vocacional y alto nivel academico.',
                'logo_path' => 'Logos de niveles educativos/logo bachillerato.png',
                'logo_extendido_path' => 'Logos de niveles educativos/Bachillerato extendido.jpeg',
                'hoja_informativa_path' => 'Hojas informativas/High school _ hoja informativa.pdf.pdf',
                'modelo_academico_path' => 'Modelos educativos/modelo educativo high.png',
                'informacion' => [
                    'titulo' => 'Un bachillerato que te reta, forma y tambien se disfruta',
                    'intro' => 'Preparacion universitaria con Programa del Diploma IB, orientacion vocacional, idiomas y proyectos reales.',
                    'destacados' => [
                        ['titulo' => 'Acompanamiento', 'texto' => 'Orientacion vocacional, asesoria para admisiones y seguimiento individual rumbo a universidad.'],
                        ['titulo' => 'Aprendizaje', 'texto' => 'Programa del Diploma IB, Teoria del Conocimiento, CAS, idiomas y pensamiento critico aplicado.'],
                        ['titulo' => 'Comunidad', 'texto' => 'DKMUN, proyectos IB, arte, deporte diario e impacto social para fortalecer iniciativa y expresion.'],
                    ],
                    'puntos' => [
                        'Bachillerato IB oficial con validez internacional.',
                        'Programa del Diploma y desarrollo del perfil IB.',
                        'Ingles, espanol y frances con 15 bloques semanales en ingles.',
                        'Mas del 70% de egresados obtiene becas en universidades de Mexico y el extranjero.',
                        'Orientacion vocacional, asesoria para admisiones y seguimiento individual.',
                    ],
                    'secciones' => [
                        ['titulo' => 'Pensamiento global', 'texto' => 'Teoria del Conocimiento y CAS fortalecen pensamiento critico, vision internacional y capacidad de tomar decisiones.'],
                        ['titulo' => 'Certificaciones e idiomas', 'texto' => 'La formacion en ingles y frances prepara para comunicar argumentos, escribir ensayos y abrir puertas universitarias.'],
                        ['titulo' => 'Debates y diplomacia', 'texto' => 'DKMUN permite negociar, argumentar, proponer soluciones y representar paises en asuntos internacionales.'],
                        ['titulo' => 'Impacto social y expresion', 'texto' => 'CAS, arte y deporte diario hacen que cada Explorer participe en proyectos culturales, sociales, ambientales o deportivos.'],
                    ],
                    'experiencias' => ['Expo Arte', 'Graduacion', 'Dia del Explorer', 'DKMUN', 'Proyectos IB'],
                ],
            ],
            'ib-en-discovery' => [
                'titulo' => 'IB en Discovery',
                'descripcion' => 'Bachillerato Internacional en Discovery: habilidades, perfil de aprendizaje y Programa del Diploma con visión global.',
                'logo_path' => 'Logos de niveles educativos/Logo IB cl.jpeg',
                'usar_placeholder_hero' => true,
                'hero_media_path' => 'Logos principales/IB Internacional.png',
                'ocultar_galeria' => true,
                'layout' => 'ib',
                'informacion' => [
                    'titulo' => 'Bachillerato Internacional en Discovery',
                    'intro' => 'Nuestro modelo educativo potencia habilidades para que los Explorers vivan el aprendizaje como un proceso activo y dinámico. El enfoque IB los impulsa a aprender a aprender, plantear buenas preguntas, establecer metas, trabajar por sus aspiraciones y sostener la determinación necesaria para cumplirlas.',
                    'destacados' => [
                        ['titulo' => 'Habilidades', 'texto' => 'Pensamiento, autogestión, comunicación, investigación y habilidades sociales para aprender con autonomía.'],
                        ['titulo' => 'Perfil IB', 'texto' => 'Formación de Explorers con capacidades humanas que van más allá del éxito académico.'],
                        ['titulo' => 'Programa del Diploma', 'texto' => 'Un programa riguroso y equilibrado para Explorers de 16 a 19 años, reconocido por universidades del mundo.'],
                    ],
                    'puntos' => [
                        'Desarrollo de pensamiento crítico, pensamiento creativo y transferencia del aprendizaje.',
                        'Autogestión con organización, manejo del tiempo, motivación y habilidades afectivas.',
                        'Comunicación para expresar ideas, escuchar, colaborar y construir acuerdos.',
                        'Investigación para comparar, contrastar, validar y priorizar información.',
                        'Habilidades sociales para relacionarse positivamente y resolver conflictos.',
                    ],
                    'imagen_enfoque' => [
                        'titulo' => 'Enfoque de aprendizaje Pacis',
                        'referencia' => 'Imagen de apoyo para los enfoques de aprendizaje IB.',
                        'media_path' => 'Enfoque de aprendizaje/Enfoque de aprendizaje Pacis.png',
                    ],
                    'secciones' => [
                        ['titulo' => 'Perfil de la comunidad de aprendizaje IB', 'texto' => 'El perfil IB expresa capacidades y responsabilidades humanas que buscan formar Explorers respetuosos consigo mismos, con las demás personas y con el mundo que les rodea.'],
                        ['titulo' => 'Programa del Diploma (PD)', 'texto' => 'Colegio Discovery está acreditado por la Organización del Bachillerato Internacional para impartir el Programa del Diploma, una propuesta que favorece amplitud y profundidad académica junto con desarrollo físico, intelectual, emocional y ético.'],
                        ['titulo' => 'Qué ofrece el PD a los Explorers', 'texto' => 'El programa promueve excelencia académica, estudio de al menos dos lenguas, desarrollo integral y exploración de la naturaleza del conocimiento mediante Teoría del Conocimiento.'],
                        ['titulo' => 'Currículo del Programa del Diploma', 'texto' => 'El currículo se integra por el tronco común del PD y seis grupos de asignaturas. Sus componentes troncales amplían la experiencia educativa y retan a los Explorers a aplicar conocimientos y habilidades.'],
                        ['titulo' => 'Perfil de nuestros egresados', 'texto' => 'Nuestros egresados se desenvuelven competitivamente en inglés y español, cuentan con preparación académica para certificaciones, enfrentan desafíos con mentalidad abierta y son ciudadanos globales con visión internacional.'],
                    ],
                    'experiencias' => ['Pensamiento crítico', 'Teoría del Conocimiento', 'CAS', 'Investigación', 'Dos lenguas', 'Mentalidad internacional'],
                ],
            ],
            'certificacion-de-ingles' => [
                'titulo' => 'Certificación de Inglés',
                'descripcion' => 'Preparación progresiva para certificar el dominio del inglés con metas claras, práctica guiada y acompañamiento académico.',
                'usar_placeholder_hero' => true,
                'hero_media_path' => 'Certificacion fotos/unicam.jpg',
                'ocultar_galeria' => true,
                'layout' => 'ingles',
                'informacion' => [
                    'titulo' => 'Certificación de Inglés en Discovery',
                    'intro' => 'La certificación de inglés acompaña a nuestros Explorers para medir, fortalecer y demostrar sus habilidades comunicativas. El trabajo se enfoca en reading, writing, listening y speaking, con seguimiento académico para avanzar hacia evaluaciones reconocidas y oportunidades universitarias.',
                    'eyebrow' => 'Certificación de Inglés',
                    'puntos_titulo' => 'Preparación integral por habilidades',
                    'destacados' => [
                        ['titulo' => 'Metas claras', 'texto' => 'Los Explorers conocen las habilidades que deben fortalecer y trabajan con objetivos medibles durante el ciclo escolar.'],
                        ['titulo' => 'Práctica integral', 'texto' => 'Reading, writing, listening y speaking se practican de forma constante para usar el idioma con seguridad.'],
                        ['titulo' => 'Proyección académica', 'texto' => 'La preparación ayuda a contar con evidencias de nivel de inglés para procesos escolares, universitarios y de movilidad.'],
                    ],
                    'puntos' => [
                        'Preparación para evaluaciones de inglés con validez académica.',
                        'Práctica guiada de comprensión lectora, escritura, comprensión auditiva y expresión oral.',
                        'Seguimiento del avance individual para detectar fortalezas y áreas de mejora.',
                        'Trabajo con vocabulario, gramática y comunicación en contextos reales.',
                        'Base para certificaciones como Cambridge, TOEFL u otros exámenes de referencia internacional.',
                    ],
                    'secciones' => [
                        ['titulo' => 'Evaluación y diagnóstico', 'texto' => 'El proceso permite identificar el nivel de cada Explorer y orientar la preparación hacia metas alcanzables, de acuerdo con sus necesidades académicas.'],
                        ['titulo' => 'Habilidades comunicativas', 'texto' => 'La preparación integra lectura, escritura, escucha y expresión oral para que cada Explorer use el inglés con precisión, fluidez y confianza.'],
                        ['titulo' => 'Acompañamiento académico', 'texto' => 'Docentes y coordinación dan seguimiento al progreso, proponen práctica específica y ayudan a que cada Explorer llegue mejor preparado a sus evaluaciones.'],
                        ['titulo' => 'Certificaciones para el futuro', 'texto' => 'Contar con una certificación de inglés abre puertas en admisiones universitarias, intercambios, becas y experiencias académicas con enfoque internacional.'],
                    ],
                    'cierre' => [
                        'titulo' => 'Evidencias de dominio para nuevas oportunidades',
                        'texto' => 'La certificación permite demostrar el nivel de inglés con mayor claridad y fortalece el perfil académico de los Explorers para procesos universitarios, becas, movilidad e intercambios.',
                    ],
                    'experiencias' => ['Reading', 'Writing', 'Listening', 'Speaking', 'Cambridge', 'TOEFL', 'Seguimiento académico'],
                ],
            ],
        ],
    ],

    'temas_niveles' => [
        'preescolar' => [
            'hero' => 'bg-lime-500 text-black',
            'heading' => 'text-lime-800',
            'eyebrow' => 'text-lime-800',
            'soft' => 'bg-lime-50 border-lime-300',
            'dot' => 'bg-lime-500',
            'button' => 'bg-lime-500 text-black hover:bg-lime-600',
            'chip' => 'text-lime-800',
            'bar' => 'bg-lime-500',
            'heroText' => 'text-black',
            'heroMuted' => 'text-black',
        ],
        'primaria' => [
            'hero' => 'bg-red-600 text-white',
            'heading' => 'text-red-600',
            'eyebrow' => 'text-red-600',
            'soft' => 'bg-red-50 border-red-200',
            'dot' => 'bg-red-600',
            'button' => 'bg-red-600 text-white hover:bg-red-700',
            'chip' => 'text-red-600',
            'bar' => 'bg-red-600',
            'heroText' => 'text-white',
            'heroMuted' => 'text-red-50',
        ],
        'secundaria' => [
            'hero' => 'bg-blue-700 text-white',
            'heading' => 'text-blue-700',
            'eyebrow' => 'text-blue-700',
            'soft' => 'bg-blue-50 border-blue-100',
            'dot' => 'bg-blue-700',
            'button' => 'bg-blue-700 text-white hover:bg-blue-800',
            'chip' => 'text-blue-700',
            'bar' => 'bg-blue-700',
            'heroText' => 'text-white',
            'heroMuted' => 'text-blue-50',
        ],
        'bachillerato' => [
            'hero' => 'bg-green-500 text-white',
            'heading' => 'text-green-600',
            'eyebrow' => 'text-green-600',
            'soft' => 'bg-green-50 border-green-200',
            'dot' => 'bg-green-500',
            'button' => 'bg-green-500 text-white hover:bg-green-600',
            'chip' => 'text-green-600',
            'bar' => 'bg-green-500',
            'heroText' => 'text-white',
            'heroMuted' => 'text-green-50',
        ],
        'ib-en-discovery' => [
            'hero' => 'bg-amber-500 text-black',
            'heading' => 'text-yellow-500',
            'eyebrow' => 'text-yellow-500',
            'soft' => 'bg-amber-50 border-amber-500',
            'dot' => 'bg-amber-500',
            'button' => 'bg-amber-500 text-black hover:bg-amber-600',
            'chip' => 'text-yellow-500',
            'bar' => 'bg-amber-500',
            'heroText' => 'text-black',
            'heroMuted' => 'text-black',
        ],
        'certificacion-de-ingles' => [
            'hero' => 'bg-sky-500 text-white',
            'heading' => 'text-sky-500',
            'eyebrow' => 'text-sky-500',
            'soft' => 'bg-sky-50 border-sky-500',
            'dot' => 'bg-sky-500',
            'button' => 'bg-sky-500 text-white hover:bg-sky-600',
            'chip' => 'text-sky-500',
            'bar' => 'bg-sky-500',
            'heroText' => 'text-white',
            'heroMuted' => 'text-sky-50',
        ],
        'default' => [
            'hero' => 'bg-blue-700 text-white',
            'heading' => 'text-blue-700',
            'eyebrow' => 'text-blue-700',
            'soft' => 'bg-blue-50 border-blue-100',
            'dot' => 'bg-blue-700',
            'button' => 'bg-blue-700 text-white hover:bg-blue-800',
            'chip' => 'text-blue-700',
            'bar' => 'bg-blue-700',
            'heroText' => 'text-white',
            'heroMuted' => 'text-blue-50',
        ],
    ],
];
